[workspace]
members = [
  "contracts/token",
  "contracts/access-control",
  "contracts/upgradeable",
  "contracts/multisig",
  "contracts/event-rich",
  "contracts/escrow",
  "contracts/vesting",
  "contracts/oracle",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "27.0.5" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
